sylius_grid:
    grids:
        cr_sylius_extended_elasticsearch_plugin_admin_search_configuration_index:
            driver:
                name: doctrine/orm
                options:
                    class: CodeRhapsodie\SyliusExtendedElasticsearchPlugin\Entity\SearchConfiguration
            fields:
                attribute:
                    type: string
                    label: ATTRIBUTE
                option:
                    type: string
                    label: OPTION
                taxon:
                    type: string
                    label: TAXON
                channel:
                    type: string
                    label: CHANNEL
                searchable:
                    type: twig
                    label: SEARCHABLE
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                filterable:
                    type: twig
                    label: FILTERABLE
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                filterOptions:
                    type: string
                    label: OPTIONS
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
