sylius_grid:
    grids:
        cr_sylius_extended_elasticsearch_plugin_admin_search_configuration_index:
            driver:
                name: doctrine/orm
                options:
                    class: CodeRhapsodie\SyliusExtendedElasticsearchPlugin\Entity\SearchConfiguration
            fields:
                attribute:
                    type: string
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.attribute
                option:
                    type: string
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.option
                taxons:
                    type: twig
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.taxon
                    options:
                        template: "@CodeRhapsodieSyliusExtendedElasticsearchPlugin/Grid/Field/taxons.html.twig"
                channels:
                    type: twig
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.channel
                    options:
                        template: "@CodeRhapsodieSyliusExtendedElasticsearchPlugin/Grid/Field/channels.html.twig"
                usedInGlobalSearch:
                    type: twig
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.used_in_global_search
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                searchable:
                    type: twig
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.searchable
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                filterable:
                    type: twig
                    label: cr_sylius_extended_elasticsearch_plugin.admin.grid.search_configuration.filterable
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
#                filterOptions:
#                    type: string
#                    label: OPTIONS
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
