cr_sylius_extended_elasticsearch_plugin_shop_list_products:
    path: /{_locale}/products-list/{slug}
    defaults:
        _controller: cr_sylius_extended_elasticsearch_plugin.controller.action.shop.list_products
        template: "@CodeRhapsodieSyliusExtendedElasticsearchPlugin/Shop/Product/index.html.twig"
    requirements:
        slug: .+

cr_sylius_extended_elasticsearch_plugin_shop_auto_complete_product_name:
    path: /{_locale}/auto-complete/product
    defaults:
        _controller: cr_sylius_extended_elasticsearch_plugin.controller.action.shop.auto_complete_product_name
    requirements:
        slug: .+

cr_sylius_extended_elasticsearch_plugin_shop_search:
    path: /{_locale}/search
    defaults:
        _controller: cr_sylius_extended_elasticsearch_plugin.controller.action.shop.search
        template: "@CodeRhapsodieSyliusExtendedElasticsearchPlugin/Shop/search.html.twig"
