winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                cr_sylius_extended_elasticsearch_plugin_index_order_products:
                    on: ["create"]
                    do: ["@cr_sylius_extended_elasticsearch_plugin.event_listener.order_products", "updateOrderProducts"]
                    args: ["object"]
